package main

import (
 "context"
 "crypto/sha256"
 "database/sql"
 "encoding/hex"
 "errors"
 "io"
 "log/slog"
 "mime"
 "net/http"
 "os"
 "path/filepath"
 "strconv"
 "strings"
 "time"

 "github.com/gin-gonic/gin"
 "github.com/google/uuid"
 _ "github.com/jackc/pgx/v5/stdlib"
 "golang.org/x/crypto/bcrypt"
 "medical-timeline/internal/storage"
)

type config struct { port, cookie, secret string; max int64 }
type app struct { db *sql.DB; store storage.Store; cfg config; log *slog.Logger }
type user struct { ID, Email, Role string }
func main(){
 c:=config{port:env("APP_PORT","8080"),cookie:"mt_session",secret:os.Getenv("SESSION_SECRET"),max:envInt("MAX_UPLOAD_BYTES",10<<20)}
 if c.secret=="" { slog.Error("SESSION_SECRET must be set"); os.Exit(1) }
 db,err:=sql.Open("pgx",os.Getenv("DATABASE_URL"));if err!=nil{panic(err)};defer db.Close();if err=db.Ping();err!=nil{panic(err)}
 st,err:=storage.NewLocal(env("STORAGE_PATH","./storage/uploads"));if err!=nil{panic(err)}
 a:=&app{db:db,store:st,cfg:c,log:slog.Default()}; r:=a.routes();a.log.Info("server starting","port",c.port);if err:=r.Run(":"+c.port);err!=nil{a.log.Error("server stopped","error",err)}
}
func env(k,d string)string{if v:=os.Getenv(k);v!=""{return v};return d};func envInt(k string,d int64)int64{v,e:=strconv.ParseInt(env(k,""),10,64);if e!=nil||v<=0{return d};return v}
func (a *app) routes()*gin.Engine { r:=gin.New();r.Use(gin.Logger(),gin.Recovery(),headers(),limit(a.cfg.max));r.Static("/css", "./web/css");r.Static("/js", "./web/js");for _,page:=range []string{"index.html","login.html","register.html","dashboard.html","documents.html","document.html","admin.html"}{p:=page;r.GET("/"+p,func(c *gin.Context){c.File(filepath.Join("web",p))})};r.GET("/",func(c *gin.Context){c.File("web/index.html")}); api:=r.Group("/api");api.POST("/auth/register",a.register);api.POST("/auth/login",a.login);api.POST("/auth/logout",a.logout); api.GET("/me",a.auth(),a.me)
 p:=api.Group("/patients",a.auth());p.POST("",a.createPatient);p.GET("",a.listPatients);p.GET("/:id",a.patient);p.POST("/:id/documents",a.upload);p.GET("/:id/documents",a.documents)
 d:=api.Group("/documents",a.auth());d.GET("/:id",a.document);d.GET("/:id/file",a.file);d.POST("/:id/deletion-request",a.deletionRequest)
 ad:=api.Group("/admin",a.auth(),a.admin());ad.GET("/stats",a.stats);ad.GET("/deletion-requests",a.requests);ad.POST("/deletion-requests/:id/approve",a.approve);ad.POST("/deletion-requests/:id/reject",a.reject);return r }
func headers()gin.HandlerFunc{return func(c *gin.Context){c.Header("X-Content-Type-Options","nosniff");c.Header("X-Frame-Options","DENY");c.Header("Referrer-Policy","no-referrer");c.Next()}}
func limit(n int64)gin.HandlerFunc{return func(c *gin.Context){c.Request.Body=http.MaxBytesReader(c.Writer,c.Request.Body,n+1024*1024);c.Next()}}
func fail(c *gin.Context,status int,code,msg string){c.AbortWithStatusJSON(status,gin.H{"error":gin.H{"code":code,"message":msg}})}
func (a *app) audit(ctx context.Context,u *user, action,typ,id string){var uid any;if u!=nil{uid=u.ID};_,_ = a.db.ExecContext(ctx,"INSERT INTO audit_logs(id,user_id,action,resource_type,resource_id) VALUES($1,$2,$3,$4,NULLIF($5,'')::uuid)",uuid.New(),uid,action,typ,id)}
func (a *app) auth()gin.HandlerFunc{return func(c *gin.Context){cookie,e:=c.Cookie(a.cfg.cookie);if e!=nil{fail(c,401,"UNAUTHENTICATED","Authentication is required.");return};h:=hash(cookie);var u user;var exp time.Time;e=a.db.QueryRowContext(c,"SELECT u.id,u.email,u.role,s.expires_at FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1",h).Scan(&u.ID,&u.Email,&u.Role,&exp);if e!=nil||time.Now().After(exp){fail(c,401,"UNAUTHENTICATED","Your session is invalid or expired.");return};c.Set("user",&u);c.Next()}}
func (a *app) admin()gin.HandlerFunc{return func(c *gin.Context){u:=current(c);if u.Role!="ADMIN"{fail(c,403,"ADMIN_REQUIRED","Administrator access is required.");return};c.Next()}}
func current(c *gin.Context)*user{return c.MustGet("user").(*user)}
func (a *app) register(c *gin.Context){var in struct{Email,Password string};if c.ShouldBindJSON(&in)!=nil||!strings.Contains(in.Email,"@")||len(in.Password)<12{fail(c,422,"INVALID_INPUT","Use a valid email and a password of at least 12 characters.");return}; h,e:=bcrypt.GenerateFromPassword([]byte(in.Password),bcrypt.DefaultCost);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to create account.");return};u:=user{ID:uuid.NewString(),Email:strings.ToLower(strings.TrimSpace(in.Email)),Role:"USER"};_,e=a.db.ExecContext(c,"INSERT INTO users(id,email,password_hash,role) VALUES($1,$2,$3,$4)",u.ID,u.Email,string(h),u.Role);if e!=nil{if strings.Contains(e.Error(),"unique"){fail(c,409,"EMAIL_EXISTS","An account with that email already exists.")}else{fail(c,500,"INTERNAL_ERROR","Unable to create account.")};return};a.audit(c,&u,"USER_REGISTERED","USER",u.ID);c.JSON(201,gin.H{"user":u})}
func (a *app) login(c *gin.Context){var in struct{Email,Password string};if c.ShouldBindJSON(&in)!=nil{fail(c,400,"INVALID_INPUT","Email and password are required.");return};var u user;var ph string;e:=a.db.QueryRowContext(c,"SELECT id,email,role,password_hash FROM users WHERE email=$1",strings.ToLower(strings.TrimSpace(in.Email))).Scan(&u.ID,&u.Email,&u.Role,&ph);if e!=nil||bcrypt.CompareHashAndPassword([]byte(ph),[]byte(in.Password))!=nil{fail(c,401,"INVALID_CREDENTIALS","Invalid email or password.");return};token:=uuid.NewString()+uuid.NewString();_,e=a.db.ExecContext(c,"INSERT INTO sessions(id,user_id,token_hash,expires_at) VALUES($1,$2,$3,$4)",uuid.New(),u.ID,hash(token),time.Now().Add(24*time.Hour));if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to start session.");return};http.SetCookie(c.Writer,&http.Cookie{Name:a.cfg.cookie,Value:token,Path:"/",HttpOnly:true,Secure:env("APP_ENV","development")=="production",SameSite:http.SameSiteLaxMode,MaxAge:86400});a.audit(c,&u,"USER_LOGIN","USER",u.ID);c.JSON(200,gin.H{"user":u})}
func (a *app) logout(c *gin.Context){if t,e:=c.Cookie(a.cfg.cookie);e==nil{_,_=a.db.ExecContext(c,"DELETE FROM sessions WHERE token_hash=$1",hash(t))};http.SetCookie(c.Writer,&http.Cookie{Name:a.cfg.cookie,Value:"",Path:"/",MaxAge:-1,HttpOnly:true,SameSite:http.SameSiteLaxMode});c.Status(204)}
func (a *app) me(c *gin.Context){c.JSON(200,gin.H{"user":current(c)})};func hash(v string)string{x:=sha256.Sum256([]byte(v));return hex.EncodeToString(x[:])}
func (a *app) createPatient(c *gin.Context){var in struct{DisplayName string `json:"display_name"`;DateOfBirth string `json:"date_of_birth"`};if c.ShouldBindJSON(&in)!=nil||strings.TrimSpace(in.DisplayName)==""{fail(c,422,"INVALID_INPUT","A display name is required.");return};var dob any;if strings.TrimSpace(in.DateOfBirth)!=""{if _,e:=time.Parse("2006-01-02",in.DateOfBirth);e!=nil{fail(c,422,"INVALID_INPUT","Date of birth must use YYYY-MM-DD.");return};dob=in.DateOfBirth}; id:=uuid.NewString();_,e:=a.db.ExecContext(c,"INSERT INTO patients(id,user_id,display_name,date_of_birth) VALUES($1,$2,$3,$4)",id,current(c).ID,strings.TrimSpace(in.DisplayName),dob);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to create patient.");return};a.audit(c,current(c),"PATIENT_CREATED","PATIENT",id);c.JSON(201,gin.H{"id":id,"display_name":in.DisplayName,"date_of_birth":in.DateOfBirth})}
func (a *app) listPatients(c *gin.Context){rows,e:=a.db.QueryContext(c,"SELECT id,display_name,date_of_birth,created_at FROM patients WHERE user_id=$1 ORDER BY created_at DESC",current(c).ID);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to retrieve patients.");return};defer rows.Close();out:=[]gin.H{};for rows.Next(){var id,n string;var dob *time.Time;var at time.Time;_ = rows.Scan(&id,&n,&dob,&at);out=append(out,gin.H{"id":id,"display_name":n,"date_of_birth":dob,"created_at":at})};c.JSON(200,gin.H{"patients":out})}
func (a *app) ownedPatient(c *gin.Context,id string)bool{var one int;e:=a.db.QueryRowContext(c,"SELECT 1 FROM patients WHERE id=$1 AND user_id=$2",id,current(c).ID).Scan(&one);return e==nil}
func (a *app) patient(c *gin.Context){id:=c.Param("id");if !a.ownedPatient(c,id){fail(c,404,"PATIENT_NOT_FOUND","The requested patient could not be found.");return};var n string;var dob *time.Time;var at time.Time;_ = a.db.QueryRowContext(c,"SELECT display_name,date_of_birth,created_at FROM patients WHERE id=$1",id).Scan(&n,&dob,&at);c.JSON(200,gin.H{"id":id,"display_name":n,"date_of_birth":dob,"created_at":at})}
func (a *app) upload(c *gin.Context){pid:=c.Param("id");if !a.ownedPatient(c,pid){fail(c,404,"PATIENT_NOT_FOUND","The requested patient could not be found.");return};f,e:=c.FormFile("file");if e!=nil{fail(c,400,"FILE_REQUIRED","Provide a document file.");return};if f.Size<=0{fail(c,422,"EMPTY_FILE","The file is empty.");return};if f.Size>a.cfg.max{fail(c,413,"FILE_TOO_LARGE","The file exceeds the upload limit.");return};ext:=strings.ToLower(filepath.Ext(f.Filename));allowed:=map[string]string{".pdf":"application/pdf",".jpg":"image/jpeg",".jpeg":"image/jpeg",".png":"image/png"};want,ok:=allowed[ext];if !ok{fail(c,422,"INVALID_FILE_TYPE","Only PDF, JPG, JPEG, and PNG files are supported.");return};src,e:=f.Open();if e!=nil{fail(c,400,"INVALID_UPLOAD","The upload could not be read.");return};defer src.Close();head:=make([]byte,512);n,_:=io.ReadFull(src,head);det:=http.DetectContentType(head[:n]);if det!=want && !(want=="image/jpeg"&&strings.HasPrefix(det,"image/jpeg")){fail(c,422,"INVALID_FILE_TYPE","The file content does not match its supported type.");return};if _,e=src.Seek(0,0);e!=nil{fail(c,400,"INVALID_UPLOAD","The upload could not be read.");return};data,e:=io.ReadAll(io.LimitReader(src,a.cfg.max+1));if e!=nil||int64(len(data))>a.cfg.max{fail(c,413,"FILE_TOO_LARGE","The file exceeds the upload limit.");return};sum:=sha256.Sum256(data);fh:=hex.EncodeToString(sum[:]);var existing string;e=a.db.QueryRowContext(c,"SELECT id FROM documents WHERE patient_id=$1 AND file_hash=$2",pid,fh).Scan(&existing);if e==nil{fail(c,409,"DUPLICATE_DOCUMENT","An identical document already exists for this patient.");return};if e!=nil&&!errors.Is(e,sql.ErrNoRows){fail(c,500,"INTERNAL_ERROR","Unable to validate upload.");return};key:=uuid.NewString();if e=a.store.Save(key,strings.NewReader(string(data)));e!=nil{fail(c,500,"STORAGE_ERROR","Unable to store the original document.");return};id:=uuid.NewString();_,e=a.db.ExecContext(c,"INSERT INTO documents(id,patient_id,original_filename,storage_key,mime_type,file_size,file_hash,uploaded_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8)",id,pid,filepath.Base(f.Filename),key,want,len(data),fh,current(c).ID);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to save document metadata.");return};a.audit(c,current(c),"DOCUMENT_UPLOADED","DOCUMENT",id);c.JSON(201,gin.H{"id":id,"status":"READY","message":"Document uploaded. Extraction will be available in a future processing phase."})}
func (a *app) documents(c *gin.Context){pid:=c.Param("id");if !a.ownedPatient(c,pid){fail(c,404,"PATIENT_NOT_FOUND","The requested patient could not be found.");return};rows,e:=a.db.QueryContext(c,"SELECT id,original_filename,mime_type,file_size,file_hash,document_type,processing_status,created_at FROM documents WHERE patient_id=$1 AND processing_status <> 'DELETED' ORDER BY created_at DESC",pid);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to retrieve documents.");return};defer rows.Close();out:=[]gin.H{};for rows.Next(){var id,n,mt,fh,dt,st string;var sz int64;var at time.Time;_ = rows.Scan(&id,&n,&mt,&sz,&fh,&dt,&st,&at);out=append(out,gin.H{"id":id,"original_filename":n,"mime_type":mt,"file_size":sz,"file_hash":fh,"document_type":dt,"processing_status":st,"created_at":at})};c.JSON(200,gin.H{"documents":out})}
func (a *app) ownedDocument(c *gin.Context,id string)(string,bool){var pid string;e:=a.db.QueryRowContext(c,"SELECT d.patient_id FROM documents d JOIN patients p ON p.id=d.patient_id WHERE d.id=$1 AND p.user_id=$2",id,current(c).ID).Scan(&pid);return pid,e==nil}
func (a *app) document(c *gin.Context){id:=c.Param("id");if _,ok:=a.ownedDocument(c,id);!ok{fail(c,404,"DOCUMENT_NOT_FOUND","The requested document could not be found.");return};var n,mt,fh,dt,st,up string;var sz int64;var at time.Time;e:=a.db.QueryRowContext(c,"SELECT d.original_filename,d.mime_type,d.file_size,d.file_hash,d.document_type,d.processing_status,d.uploaded_by,d.created_at FROM documents d WHERE d.id=$1",id).Scan(&n,&mt,&sz,&fh,&dt,&st,&up,&at);if e!=nil{fail(c,404,"DOCUMENT_NOT_FOUND","The requested document could not be found.");return};a.audit(c,current(c),"DOCUMENT_VIEWED","DOCUMENT",id);c.JSON(200,gin.H{"id":id,"original_filename":n,"mime_type":mt,"file_size":sz,"file_hash":fh,"document_type":dt,"processing_status":st,"uploaded_by":up,"created_at":at})}
func (a *app) file(c *gin.Context){id:=c.Param("id");if _,ok:=a.ownedDocument(c,id);!ok{fail(c,404,"DOCUMENT_NOT_FOUND","The requested document could not be found.");return};var key,n,mt,st string;e:=a.db.QueryRowContext(c,"SELECT storage_key,original_filename,mime_type,processing_status FROM documents WHERE id=$1",id).Scan(&key,&n,&mt,&st);if e!=nil||st=="DELETED"{fail(c,404,"DOCUMENT_NOT_FOUND","The requested document could not be found.");return};f,e:=a.store.Open(key);if e!=nil{fail(c,404,"FILE_NOT_FOUND","The original file is unavailable.");return};defer f.Close();c.Header("Content-Disposition",mime.FormatMediaType("inline",map[string]string{"filename":n}));c.DataFromReader(200,-1,mt,f,nil)}
func (a *app) deletionRequest(c *gin.Context){id:=c.Param("id");if _,ok:=a.ownedDocument(c,id);!ok{fail(c,404,"DOCUMENT_NOT_FOUND","The requested document could not be found.");return};var in struct{Reason string `json:"reason"`};_ = c.ShouldBindJSON(&in);tx,e:=a.db.BeginTx(c,nil);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to request deletion.");return};defer tx.Rollback();r:=uuid.NewString();_,e=tx.ExecContext(c,"INSERT INTO deletion_requests(id,document_id,requested_by,reason) VALUES($1,$2,$3,$4)",r,id,current(c).ID,strings.TrimSpace(in.Reason));if e==nil{_,e=tx.ExecContext(c,"UPDATE documents SET processing_status='DELETION_REQUESTED',deletion_requested_at=now(),deletion_requested_by=$1,deletion_reason=$2,updated_at=now() WHERE id=$3",current(c).ID,strings.TrimSpace(in.Reason),id)};if e!=nil{if strings.Contains(e.Error(),"unique"){fail(c,409,"DELETION_ALREADY_REQUESTED","A deletion request already exists.")}else{fail(c,500,"INTERNAL_ERROR","Unable to request deletion.")};return};if e=tx.Commit();e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to request deletion.");return};a.audit(c,current(c),"DELETION_REQUESTED","DOCUMENT",id);c.JSON(201,gin.H{"id":r,"status":"PENDING"})}
func (a *app) stats(c *gin.Context){var users,patients,docs,today,pending,failed int; e:=a.db.QueryRowContext(c,"SELECT (SELECT count(*) FROM users),(SELECT count(*) FROM patients),(SELECT count(*) FROM documents),(SELECT count(*) FROM documents WHERE created_at >= current_date),(SELECT count(*) FROM deletion_requests WHERE status='PENDING'),(SELECT count(*) FROM documents WHERE processing_status='FAILED')").Scan(&users,&patients,&docs,&today,&pending,&failed);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to retrieve administration data.");return};c.JSON(200,gin.H{"total_users":users,"total_patients":patients,"total_documents":docs,"documents_uploaded_today":today,"pending_deletion_requests":pending,"failed_documents":failed})}
func (a *app) requests(c *gin.Context){rows,e:=a.db.QueryContext(c,"SELECT r.id,r.document_id,d.original_filename,u.email,r.created_at,r.reason,r.status FROM deletion_requests r JOIN documents d ON d.id=r.document_id JOIN users u ON u.id=r.requested_by ORDER BY r.created_at DESC");if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to retrieve deletion requests.");return};defer rows.Close();out:=[]gin.H{};for rows.Next(){var id,did,n,email,reason,status string;var at time.Time;_ = rows.Scan(&id,&did,&n,&email,&at,&reason,&status);out=append(out,gin.H{"id":id,"document_id":did,"document":n,"requested_by":email,"requested_at":at,"reason":reason,"status":status})};c.JSON(200,gin.H{"deletion_requests":out})}
func (a *app) review(c *gin.Context,approved bool){rid:=c.Param("id");tx,e:=a.db.BeginTx(c,nil);if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to review deletion request.");return};defer tx.Rollback();var did string;e=tx.QueryRowContext(c,"SELECT document_id FROM deletion_requests WHERE id=$1 AND status='PENDING' FOR UPDATE",rid).Scan(&did);if e!=nil{fail(c,404,"DELETION_REQUEST_NOT_FOUND","The pending deletion request could not be found.");return};status:="REJECTED";event:="DELETION_REJECTED";if approved{status="APPROVED";event="DELETION_APPROVED"};_,e=tx.ExecContext(c,"UPDATE deletion_requests SET status=$1,reviewed_by=$2,reviewed_at=now() WHERE id=$3",status,current(c).ID,rid);if e==nil{if approved{_,e=tx.ExecContext(c,"UPDATE documents SET processing_status='DELETED',deleted_at=now(),deleted_by=$1,updated_at=now() WHERE id=$2",current(c).ID,did)}else{_,e=tx.ExecContext(c,"UPDATE documents SET processing_status='READY',updated_at=now() WHERE id=$1",did)}};if e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to review deletion request.");return};if e=tx.Commit();e!=nil{fail(c,500,"INTERNAL_ERROR","Unable to review deletion request.");return};a.audit(c,current(c),event,"DOCUMENT",did);c.JSON(200,gin.H{"status":status})}
func (a *app) approve(c *gin.Context){a.review(c,true)};func (a *app) reject(c *gin.Context){a.review(c,false)}
